# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('ANGER', 'anger'), ('DISGUST', 'disgust'), ('ENJOYMENT', 'enjoyment'), ('FEAR', 'fear'), ('SADNESS', 'sadness')], editable=False, max_length=256, unique=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.MainFeelingCategory')),
            ],
            options={
                'verbose_name_plural': 'Emotion Categories',
            },
        ),
        migrations.CreateModel(
            name='MentalStateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('AVERSION', 'aversion'), ('CONFUSION', 'confusion'), ('CONNECTED', 'connected'), ('DISCONNECTED', 'disconnected'), ('GRASPING', 'grasping'), ('SURPRISE', 'surprise')], editable=False, max_length=256, unique=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.MainFeelingCategory')),
            ],
            options={
                'verbose_name_plural': 'Mental State Categories',
            },
        ),
        migrations.CreateModel(
            name='PhysicalStateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('ENERGY', 'energy'), ('FOOD/DRINK', 'food/drink'), ('PAIN/PLEASURE', 'pain/pleasure'), ('TEMPERATURE', 'temperature')], editable=False, max_length=256, unique=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.MainFeelingCategory')),
            ],
            options={
                'verbose_name_plural': 'Physical State Categories',
            },
        ),
    ]
