# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 03:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0005_auto_20180108_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeelingsNeedsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('public', models.BooleanField(default=False)),
                ('feeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Feeling')),
            ],
            options={
                'verbose_name': 'feelings-needs entry',
                'verbose_name_plural': 'feelings-needs entries',
            },
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('COMMUNITY', 'community'), ('CREATIVITY', 'creativity'), ('FREEDOM', 'freedom'), ('LOVE', 'love'), ('MEANING/PURPOSE', 'meaning/purpose'), ('PROTECTION', 'protection'), ('REST', 'rest'), ('SUBSISTENCE', 'subsistence'), ('UNDERSTANDING', 'understanding')], editable=False, max_length=256, unique=True)),
                ('name', models.CharField(choices=[('EQUALITY', 'equality'), ('FAMILY', 'family'), ('MUTUALITY', 'mutuality'), ('FRIENDSHIP', 'friendship'), ('SUPPORT', 'support'), ('COLLABORATION', 'collaboration'), ('ACKNOWLEDGMENT', 'acknowledgment'), ('COOPERATION', 'cooperation'), ('PARTNERSHIP', 'partnership'), ('BELONGING', 'belonging'), ('INCLUSION', 'inclusion'), ('LEARNING', 'learning'), ('DISCOVERY', 'discovery'), ('SELF-EXPRESSION', 'self-expression'), ('STIMULATION', 'stimulation'), ('GROWTH', 'growth'), ('CELEBRATION OF LIFE', 'celebration of life'), ('INSPIRATION', 'inspiration'), ('CHOICE', 'choice'), ('AUTONOMY', 'autonomy'), ('SPONTANEITY', 'spontaneity'), ('INDEPENDENCE', 'independence'), ('ASSERTIVENESS', 'assertiveness'), ('DIFFERENTIATION', 'differentiation'), ('CONNECTION', 'connection'), ('ACCEPTANCE', 'acceptance'), ('AFFECTION', 'affection'), ('APPRECIATION', 'appreciation'), ('COMMUNICATION', 'communication'), ('CLOSENESS', 'closeness'), ('COMPANIONSHIP', 'companionship'), ('COMPASSION', 'compassion'), ('CONSIDERATION', 'consideration'), ('INTIMACY', 'intimacy'), ('MUTUALITY', 'mutuality'), ('NURTURING', 'nurturing'), ('RESPECT', 'respect'), ('SELF-RESPECT', 'self-respect'), ('SELF-ESTEEM', 'self-esteem'), ('TOUCH', 'touch'), ('PARTICIPATION', 'participation'), ('CHALLENGE', 'challenge'), ('COMPETENCE', 'competence'), ('CONSCIOUSNESS', 'consciousness'), ('CONTRIBUTION', 'contribution'), ('EFFICACY', 'efficacy'), ('EFFECTIVENESS', 'effectiveness'), ('FOCUS', 'focus'), ('HOPE', 'hope'), ('TO MATTER', 'to matter'), ('SAFETY', 'safety'), ('SECURITY', 'security'), ('STABILITY', 'stability'), ('PREDICTABILITY', 'predictability'), ('CONSISTENCY', 'consistency'), ('TRUST', 'trust'), ('REASSURANCE', 'reassurance'), ('PEACE', 'peace'), ('COMMUNION', 'communion'), ('EASE', 'ease'), ('HOPE', 'hope'), ('HEALING', 'healing'), ('HARMONY', 'harmony'), ('COMFORT', 'comfort'), ('ORDER', 'order'), ('STRUCTURE', 'structure'), ('HONESTY', 'honesty'), ('AUTHENTICITY', 'authenticity'), ('INTEGRITY', 'integrity'), ('WHOLENESS', 'wholeness'), ('FAIRNESS', 'fairness'), ('JUSTICE', 'justice'), ('PLAY', 'play'), ('JOY', 'joy'), ('HUMOR', 'humor'), ('EXPRESSION', 'expression'), ('ALIVENESS', 'aliveness'), ('BEAUTY', 'beauty'), ('CELEBRATION', 'celebration'), ('MOURNING', 'mourning'), ('LEISURE', 'leisure'), ('AWARENESS', 'awareness'), ('PRESENCE', 'presence'), ('GROUNDEDNESS', 'groundedness'), ('AIR', 'air'), ('FOOD', 'food'), ('MOVEMENT/EXERCISE', 'movement/exercise'), ('SLEEP', 'sleep'), ('SHELTER', 'shelter'), ('WATER', 'water'), ('EMPATHY', 'empathy'), ('SUPPORT', 'support'), ('TO KNOW AND BE KNOWN', 'to know and be known'), ('TO SEE/HEAR AND BE SEEN/HEARD', 'to see/hear and be seen/heard'), ('TO UNDERSTAND AND BE UNDERSTOOD', 'to understand and be understood'), ('BE UNDERSTOOD', 'be understood'), ('HONOR', 'honor'), ('RESPECT', 'respect'), ('INFORMATION', 'information'), ('CLARITY', 'clarity')], editable=False, max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='feelingsneedsentry',
            name='need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Need'),
        ),
        migrations.AddField(
            model_name='feelingsneedsentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
