# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20180108_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='category',
            field=models.CharField(choices=[('COMMUNITY', 'community'), ('CREATIVITY', 'creativity'), ('FREEDOM', 'freedom'), ('LOVE', 'love'), ('MEANING/PURPOSE', 'meaning/purpose'), ('PROTECTION', 'protection'), ('REST', 'rest'), ('SUBSISTENCE', 'subsistence'), ('UNDERSTANDING', 'understanding')], editable=False, max_length=256),
        ),
    ]
