# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_auto_20180108_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='name',
            field=models.CharField(choices=[('EQUALITY', 'equality'), ('FAMILY', 'family'), ('MUTUALITY', 'mutuality'), ('FRIENDSHIP', 'friendship'), ('SUPPORT', 'support'), ('COLLABORATION', 'collaboration'), ('ACKNOWLEDGMENT', 'acknowledgment'), ('COOPERATION', 'cooperation'), ('PARTNERSHIP', 'partnership'), ('BELONGING', 'belonging'), ('INCLUSION', 'inclusion'), ('LEARNING', 'learning'), ('DISCOVERY', 'discovery'), ('SELF-EXPRESSION', 'self-expression'), ('STIMULATION', 'stimulation'), ('GROWTH', 'growth'), ('CELEBRATION OF LIFE', 'celebration of life'), ('INSPIRATION', 'inspiration'), ('CHOICE', 'choice'), ('AUTONOMY', 'autonomy'), ('SPONTANEITY', 'spontaneity'), ('INDEPENDENCE', 'independence'), ('ASSERTIVENESS', 'assertiveness'), ('DIFFERENTIATION', 'differentiation'), ('CONNECTION', 'connection'), ('ACCEPTANCE', 'acceptance'), ('AFFECTION', 'affection'), ('APPRECIATION', 'appreciation'), ('COMMUNICATION', 'communication'), ('CLOSENESS', 'closeness'), ('COMPANIONSHIP', 'companionship'), ('COMPASSION', 'compassion'), ('CONSIDERATION', 'consideration'), ('INTIMACY', 'intimacy'), ('MUTUALITY', 'mutuality'), ('NURTURING', 'nurturing'), ('RESPECT', 'respect'), ('SELF-RESPECT', 'self-respect'), ('SELF-ESTEEM', 'self-esteem'), ('TOUCH', 'touch'), ('PARTICIPATION', 'participation'), ('CHALLENGE', 'challenge'), ('COMPETENCE', 'competence'), ('CONSCIOUSNESS', 'consciousness'), ('CONTRIBUTION', 'contribution'), ('EFFICACY', 'efficacy'), ('EFFECTIVENESS', 'effectiveness'), ('FOCUS', 'focus'), ('HOPE', 'hope'), ('TO MATTER', 'to matter'), ('SAFETY', 'safety'), ('SECURITY', 'security'), ('STABILITY', 'stability'), ('PREDICTABILITY', 'predictability'), ('CONSISTENCY', 'consistency'), ('TRUST', 'trust'), ('REASSURANCE', 'reassurance'), ('PEACE', 'peace'), ('COMMUNION', 'communion'), ('EASE', 'ease'), ('HOPE', 'hope'), ('HEALING', 'healing'), ('HARMONY', 'harmony'), ('COMFORT', 'comfort'), ('ORDER', 'order'), ('STRUCTURE', 'structure'), ('HONESTY', 'honesty'), ('AUTHENTICITY', 'authenticity'), ('INTEGRITY', 'integrity'), ('WHOLENESS', 'wholeness'), ('FAIRNESS', 'fairness'), ('JUSTICE', 'justice'), ('PLAY', 'play'), ('JOY', 'joy'), ('HUMOR', 'humor'), ('EXPRESSION', 'expression'), ('ALIVENESS', 'aliveness'), ('BEAUTY', 'beauty'), ('CELEBRATION', 'celebration'), ('MOURNING', 'mourning'), ('LEISURE', 'leisure'), ('AWARENESS', 'awareness'), ('PRESENCE', 'presence'), ('GROUNDEDNESS', 'groundedness'), ('AIR', 'air'), ('FOOD', 'food'), ('MOVEMENT/EXERCISE', 'movement/exercise'), ('SLEEP', 'sleep'), ('SHELTER', 'shelter'), ('WATER', 'water'), ('EMPATHY', 'empathy'), ('SUPPORT', 'support'), ('TO KNOW AND BE KNOWN', 'to know and be known'), ('TO SEE/HEAR AND BE SEEN/HEARD', 'to see/hear and be seen/heard'), ('TO UNDERSTAND AND BE UNDERSTOOD', 'to understand and be understood'), ('BE UNDERSTOOD', 'be understood'), ('HONOR', 'honor'), ('RESPECT', 'respect'), ('INFORMATION', 'information'), ('CLARITY', 'clarity')], editable=False, max_length=256),
        ),
    ]
