# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 00:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20180108_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feelingsneedsentry',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
