# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 20:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_auto_20180115_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feelingsneedsentry',
            name='user',
            field=models.ForeignKey(choices=[(1, 'kellysingh'), (3, 'user_1')], on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
