# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0017_auto_20180128_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeelingLeaf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FeelingMainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FeelingSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=256)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.FeelingMainCategory')),
            ],
        ),
        migrations.CreateModel(
            name='NeedCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='NeedLeaf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=256)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.NeedCategory')),
            ],
        ),
        migrations.AddField(
            model_name='feelingleaf',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.FeelingSubCategory'),
        ),
    ]
