# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0018_auto_20180128_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('public', models.CharField(choices=[('FALSE', 'false'), ('TRUE', 'true')], default='FALSE', max_length=5)),
                ('feeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.FeelingLeaf')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.NeedLeaf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
