# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0021_auto_20180128_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='need',
        ),
        migrations.AddField(
            model_name='entry',
            name='need_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='entries.NeedCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feelingleaf',
            name='sub_category',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='entries.FeelingSubCategory'),
        ),
        migrations.AlterField(
            model_name='feelingsubcategory',
            name='main_category',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='entries.FeelingMainCategory'),
        ),
        migrations.AlterField(
            model_name='needleaf',
            name='category',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='entries.NeedCategory'),
        ),
    ]
