# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0022_auto_20180128_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='feeling_main_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='entries.FeelingMainCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='feeling_sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='feeling_main_category', chained_model_field='feeling_main_category', default=None, on_delete=django.db.models.deletion.CASCADE, to='entries.FeelingSubCategory'),
        ),
        migrations.AddField(
            model_name='entry',
            name='need',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='need_category', chained_model_field='need_category', default=None, on_delete=django.db.models.deletion.CASCADE, to='entries.NeedLeaf'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='feeling',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='feeling_sub_category', chained_model_field='feeling_sub_category', default=None, on_delete=django.db.models.deletion.CASCADE, to='entries.FeelingLeaf'),
        ),
    ]
