# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 11:20
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0024_auto_20180128_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='feeling',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='feeling_sub_category', chained_model_field='feeling_sub_category', on_delete=django.db.models.deletion.CASCADE, to='entries.FeelingLeaf'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='feeling_sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='feeling_main_category', chained_model_field='feeling_main_category', on_delete=django.db.models.deletion.CASCADE, to='entries.FeelingSubCategory'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='need',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='need_category', chained_model_field='need_category', on_delete=django.db.models.deletion.CASCADE, to='entries.NeedLeaf'),
        ),
        migrations.AlterField(
            model_name='feelingleaf',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='main_category', chained_model_field='main_category', on_delete=django.db.models.deletion.CASCADE, to='entries.FeelingSubCategory'),
        ),
    ]
