# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0026_auto_20180128_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feelingleaf',
            options={'verbose_name_plural': 'Feeling Leaves'},
        ),
        migrations.AlterModelOptions(
            name='needleaf',
            options={'verbose_name_plural': 'Need Leaves'},
        ),
        migrations.RenameField(
            model_name='feelingleaf',
            old_name='name',
            new_name='feeling_leaf',
        ),
        migrations.RenameField(
            model_name='feelingleaf',
            old_name='main_category',
            new_name='feeling_main_category',
        ),
        migrations.RenameField(
            model_name='feelingmaincategory',
            old_name='name',
            new_name='feeling_main_category',
        ),
        migrations.RenameField(
            model_name='feelingsubcategory',
            old_name='main_category',
            new_name='feeling_main_category',
        ),
        migrations.RenameField(
            model_name='feelingsubcategory',
            old_name='name',
            new_name='feeling_sub_category',
        ),
        migrations.RenameField(
            model_name='needcategory',
            old_name='name',
            new_name='need_category',
        ),
        migrations.RenameField(
            model_name='needleaf',
            old_name='category',
            new_name='need_category',
        ),
        migrations.RenameField(
            model_name='needleaf',
            old_name='name',
            new_name='need_leaf',
        ),
        migrations.RemoveField(
            model_name='feelingleaf',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='feelingleaf',
            name='feeling_sub_category',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='entries.FeelingSubCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='feeling',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='feeling_sub_category', chained_model_field='feeling_sub_category', on_delete=django.db.models.deletion.CASCADE, to='entries.FeelingLeaf'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='feeling_sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='feeling_main_category', chained_model_field='feeling_main_category', on_delete=django.db.models.deletion.CASCADE, to='entries.FeelingSubCategory'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='need',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='need_category', chained_model_field='need_category', on_delete=django.db.models.deletion.CASCADE, to='entries.NeedLeaf'),
        ),
    ]
