# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0027_auto_20180129_0518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feelingleaf',
            options={},
        ),
        migrations.AlterModelOptions(
            name='needleaf',
            options={},
        ),
        migrations.AlterField(
            model_name='entry',
            name='feeling_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.FeelingSubCategory'),
        ),
    ]
