# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 06:38
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0028_auto_20180129_0539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feelingleaf',
            options={'verbose_name_plural': 'Feeling Leaves'},
        ),
        migrations.AlterModelOptions(
            name='feelingmaincategory',
            options={'verbose_name_plural': 'Feeling Main Categories'},
        ),
        migrations.AlterModelOptions(
            name='needleaf',
            options={'verbose_name_plural': 'Need Leaves'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='feeling_sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='feeling_main_category', chained_model_field='feeling_main_category', on_delete=django.db.models.deletion.CASCADE, to='entries.FeelingSubCategory'),
        ),
    ]
