# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0029_auto_20180129_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feelingsneedsentry',
            name='feeling',
        ),
        migrations.RemoveField(
            model_name='feelingsneedsentry',
            name='need',
        ),
        migrations.RemoveField(
            model_name='feelingsneedsentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='Feeling',
        ),
        migrations.DeleteModel(
            name='FeelingsNeedsEntry',
        ),
        migrations.DeleteModel(
            name='Need',
        ),
    ]
